export const palette = {
  obsidian: "#0B0F14",
  navy: "#1C2E4A",
  ivory: "#EDE6D6",
  teal: "#00A6A6",
  amber: "#F4A24C",
  ember: "#C0492B",
  blue: "#4C8ED9",
};

export const proofStats = [
  { value: "16 years", label: "front line to the C-suite", icon: "calendar" },
  { value: "~80K conversations", label: "customer insight foundation", icon: "messages" },
  { value: "6 sectors · 2 countries", label: "Bangladesh and the United States", icon: "world" },
  { value: "21 evidence points", label: "each with a number", icon: "ledger" },
];

export const insights = [
  { id: "customer-conversations", label: "Customer conversations", sublabel: "~80K conversations", icon: "users" },
  { id: "behavior-signals", label: "Behavior signals", sublabel: "Observed patterns from real users", icon: "radar" },
  { id: "market-context", label: "Market context", sublabel: "Trends, competitors and needs", icon: "world" },
  { id: "service-experience", label: "Service experience", sublabel: "Frontline learning across channels", icon: "service" },
];

export const levers = [
  { id: "brand-strategy", label: "Brand + strategy", sublabel: "Positioning, category and growth play", icon: "strategy" },
  { id: "digital-gtm", label: "Digital + GTM", sublabel: "Acquisition, activation and conversion", icon: "digital" },
  { id: "revenue-growth", label: "Revenue growth", sublabel: "Unit economics and profit impact", icon: "revenue" },
  { id: "operations", label: "Operations", sublabel: "Process, people and performance", icon: "operations" },
  { id: "ai-systems", label: "AI-enabled systems", sublabel: "Data, automation and intelligence", icon: "ai" },
  { id: "health-communication", label: "Health communication", sublabel: "Behavior change and message design", icon: "health" },
];

export const outcomes = [
  { id: "market-leadership", label: "#1 globally for growth", sublabel: "Market leadership achieved", icon: "trophy", tone: "amber" },
  { id: "reach-access", label: "Reach + access", sublabel: "People reached at scale", icon: "reach", tone: "amber" },
  { id: "revenue-pnl", label: "Revenue + P&L", sublabel: "Top-line and bottom-line improvement", icon: "revenue", tone: "blue" },
  { id: "product-operations", label: "Product + operations", sublabel: "Better products, smarter systems", icon: "operations", tone: "blue" },
  { id: "behavior-brand", label: "Behavior + brand", sublabel: "Trust, adoption and perception", icon: "radar", tone: "blue" },
  { id: "human-health", label: "Human health outcomes", sublabel: "Health, prevention and protection", icon: "health", tone: "teal" },
];

export const experience = [
  {
    id: "hsrep",
    role: "HSREP: Health System Resilience & Economic Protection",
    company: "Independent public-health platform",
    tenure: "Feb 2026 to present",
    location: "Ypsilanti, MI & Dhaka",
    market: "both",
    sector: "Public health",
    year: 2026,
    mandate: "Translate health-system evidence into clear, usable public-health communication across two markets.",
    proof: "57,274 gross platform-reported views and impressions at $0 ad spend across a two-country, eight-week Season 1.",
  },
  {
    id: "emu-housing",
    role: "Graduate Hall Director",
    company: "EMU Housing & Residence Life",
    tenure: "Jul 2025 to May 2026",
    location: "Ypsilanti, MI",
    market: "us",
    sector: "Education",
    year: 2025,
    mandate: "Lead a residence-life team and build communication systems that strengthen resident connection and crisis readiness.",
    proof: "Supervised 9 Resident Advisors serving 230 residents; 541 logged engagements and a 39.1% connection rate.",
  },
  {
    id: "emu-health",
    role: "Graduate Assistant, Health Promotion",
    company: "Eastern Michigan University, Office of Health Promotion",
    tenure: "Aug 2024 to Jul 2025",
    location: "Ypsilanti, MI",
    market: "us",
    sector: "Public health",
    year: 2024,
    mandate: "Design and promote evidence-based campus health programs grounded in behavioral science.",
    proof: "Built a year-long evaluated alcohol and cannabis harm-reduction campaign and co-created WellNest Watch.",
  },
  {
    id: "brac-uihp",
    role: "Startup Mentor, University Innovation Hub Program",
    company: "BRAC University (UIHP)",
    tenure: "Mar 2024 to May 2024",
    location: "Dhaka, Bangladesh",
    market: "bd",
    sector: "Education",
    year: 2024,
    mandate: "Mentor early-stage teams on business models, product strategy, scaling and competitive positioning.",
    proof: "Applied growth and digital-transformation methods across healthcare and technology ventures.",
  },
  {
    id: "lasertreat",
    role: "Chief Operating Officer",
    company: "Laser Treat Group",
    tenure: "Nov 2023 to Aug 2024",
    location: "Dhaka, Bangladesh",
    market: "bd",
    sector: "Specialized healthcare",
    year: 2023,
    mandate: "Stabilize and grow a multi-entity clinical group by digitizing operations and sharpening the service portfolio.",
    proof: "+16% YTD revenue, +13% retention and $0.5M annual operating-cost reduction.",
  },
  {
    id: "praava",
    role: "Head of Marketing & Corporate Sales (Head of Consumer Business)",
    company: "Praava Health",
    tenure: "Jun 2021 to Oct 2023",
    location: "Dhaka, Bangladesh",
    market: "bd",
    sector: "Primary healthcare",
    year: 2021,
    mandate: "Own the consumer P&L and shift the business from COVID dependence to durable core-care growth.",
    proof: "~57% B2C CAGR; corporate clients scaled 342 → ~1,400; consumer portfolio carried 83% of revenue.",
  },
  {
    id: "acca",
    role: "Senior Manager, Employer & Member Affairs (Team Lead)",
    company: "ACCA",
    tenure: "Jan 2019 to May 2021",
    location: "Dhaka, Bangladesh",
    market: "bd",
    sector: "Professional education",
    year: 2019,
    mandate: "Build a sustainable country business ecosystem and grow members, affiliates and approved employers against hard targets.",
    proof: "Delivered 100% of 2020-21 targets, +15.1% new-member conversion and 98.2% retention.",
  },
  {
    id: "samsung",
    role: "Manager, Product Planning",
    company: "Samsung India Electronics Ltd (Bangladesh)",
    tenure: "Sep 2017 to Dec 2018",
    location: "Dhaka, Bangladesh",
    market: "bd",
    sector: "Consumer technology",
    year: 2017,
    mandate: "Lead portfolio, pricing, positioning and go-to-market for flagship and mid-high smartphone segments.",
    proof: "Galaxy Note9 launch reached 1.54× YoY growth and ranked #1 globally for growth; J2 portfolio reached ~2,600 units/day.",
  },
  {
    id: "ekhanei",
    role: "Brand & Communications Manager (Brand & Vehicle Category Lead)",
    company: "Ekhanei.com (SnT Bangladesh)",
    tenure: "Oct 2016 to Sep 2017",
    location: "Dhaka, Bangladesh",
    market: "bd",
    sector: "E-commerce",
    year: 2016,
    mandate: "Build and lead the vehicle category for an online marketplace and own brand communications.",
    proof: "Built Bangladesh's #1 motorbike category from zero in 2.5 months and drove 25% category revenue growth.",
  },
  {
    id: "surecash",
    role: "Marketing Manager (Marketing Lead)",
    company: "SureCash (Progoti Systems Ltd)",
    tenure: "Jun 2015 to Oct 2016",
    location: "Dhaka, Bangladesh",
    market: "bd",
    sector: "Fintech & government",
    year: 2015,
    mandate: "Own brand, trade and digital for a multi-bank mobile-financial-services platform and population-scale G2P program.",
    proof: "Led the government stipend campaign reaching ~10M beneficiaries and won the Banking Fair Award of Excellence.",
  },
  {
    id: "asiatic",
    role: "Senior Executive, Strategic Planning (ATL & Digital)",
    company: "Asiatic (Bangladesh JWT) / Asiatic Digital",
    tenure: "Dec 2013 to May 2015",
    location: "Dhaka, Bangladesh",
    market: "bd",
    sector: "Advertising & digital",
    year: 2013,
    mandate: "Plan integrated campaigns and help build the agency's new digital practice.",
    proof: "Scaled the digital practice to ~$1M monthly revenue within seven months and led a six-person team.",
  },
  {
    id: "mgh",
    role: "Executive, Brand",
    company: "MGH Group",
    tenure: "May 2013 to Nov 2013",
    location: "Dhaka, Bangladesh",
    market: "bd",
    sector: "Corporate brand",
    year: 2013,
    mandate: "Build a coherent group-brand system across logistics, shipping, aviation, restaurant and radio businesses.",
    proof: "Managed domestic and overseas vendors and major sponsor activations with end-to-end quality control.",
  },
  {
    id: "grey",
    role: "Account Executive",
    company: "Grey Advertising (Grey Dhaka · WPP)",
    tenure: "Oct 2011 to May 2013",
    location: "Dhaka, Bangladesh",
    market: "bd",
    sector: "Advertising",
    year: 2011,
    mandate: "Translate consumer and production insight into brand strategy, campaigns and reliable client delivery.",
    proof: "Owned Akij F&B and GSK portfolios with 95% client retention and delivered 10+ launches.",
  },
  {
    id: "grameenphone",
    role: "Customer Manager",
    company: "Grameenphone Ltd (Telenor Bangladesh)",
    tenure: "May 2009 to Oct 2011",
    location: "Dhaka, Bangladesh",
    market: "bd",
    sector: "Telecom",
    year: 2009,
    mandate: "Understand customer behavior from the front line across premium, roaming, retailer and mass segments.",
    proof: "Handled 90-100 interactions daily with 90%+ CSAT and 85% first-call resolution, approximately 80,000 conversations.",
  },
];

const tenureByOrg = {
  Samsung: "Sep 2017 to Dec 2018",
  Praava: "Jun 2021 to Oct 2023",
  "Laser Treat": "Nov 2023 to Aug 2024",
  HSREP: "Feb 2026 to present",
  EMU: "Aug 2024 to May 2026",
  SureCash: "Jun 2015 to Oct 2016",
  Ekhanei: "Oct 2016 to Sep 2017",
  ACCA: "Jan 2019 to May 2021",
  Asiatic: "Dec 2013 to May 2015",
};

export const evidence = [
  {
    id: "samsung-note9", organization: "Samsung", organizationLabel: "Samsung / Consumer tech", sector: "Consumer technology", market: "bd", year: 2018, lens: "Growth",
    metric: "1.54× YoY · #1 globally for growth", title: "Galaxy Note9 flagship launch",
    summary: "Portfolio, pricing, positioning and launch execution produced the world's highest growth rate for the Note9 launch.",
    insights: ["market-context", "behavior-signals"], levers: ["brand-strategy", "digital-gtm", "revenue-growth"], outcomes: ["market-leadership", "revenue-pnl", "behavior-brand"],
  },
  {
    id: "samsung-j2", organization: "Samsung", organizationLabel: "Samsung / Consumer tech", sector: "Consumer technology", market: "bd", year: 2018, lens: "Growth",
    metric: "~2,600 units/day", title: "Galaxy J2 mass-market entry",
    summary: "Localized product planning and GTM turned an entry-segment portfolio into daily volume at national scale.",
    insights: ["market-context", "behavior-signals"], levers: ["brand-strategy", "digital-gtm", "revenue-growth"], outcomes: ["reach-access", "revenue-pnl"],
  },
  {
    id: "samsung-online", organization: "Samsung", organizationLabel: "Samsung / Consumer tech", sector: "Consumer technology", market: "bd", year: 2018, lens: "Health-Tech",
    metric: "New channel · loyalty", title: "E-commerce channel + loyalty",
    summary: "Built Samsung's online footprint, online-specific SKUs and a market-first consumer loyalty program.",
    insights: ["service-experience", "behavior-signals"], levers: ["digital-gtm", "ai-systems"], outcomes: ["product-operations", "behavior-brand"],
  },
  {
    id: "praava-hypergrowth", organization: "Praava", organizationLabel: "Praava / Primary healthcare", sector: "Primary healthcare", market: "bd", year: 2023, lens: "Growth",
    metric: "~45% overall · ~57% B2C CAGR", title: "Healthcare consumer-business hypergrowth",
    summary: "A data-led product and growth system shifted the consumer business from pandemic demand to durable core care.",
    insights: ["customer-conversations", "behavior-signals", "service-experience"], levers: ["brand-strategy", "digital-gtm", "revenue-growth", "operations"], outcomes: ["revenue-pnl", "reach-access", "human-health"],
  },
  {
    id: "praava-corporate", organization: "Praava", organizationLabel: "Praava / Primary healthcare", sector: "Primary healthcare", market: "bd", year: 2023, lens: "Growth",
    metric: "342 → ~1,400 clients", title: "Corporate-sales engine built from zero",
    summary: "A telco-style key-account model scaled corporate clients and grew non-COVID corporate health programs 3.1×.",
    insights: ["market-context", "service-experience"], levers: ["brand-strategy", "revenue-growth", "operations"], outcomes: ["revenue-pnl", "reach-access"],
  },
  {
    id: "praava-lifebuoy", organization: "Praava", organizationLabel: "Praava / Primary healthcare", sector: "Primary healthcare", market: "bd", year: 2021, lens: "Population Health",
    metric: "~3,000 calls/day", title: "Population access via Lifebuoy",
    summary: "A high-volume hotline and public-health coordination expanded access during the pandemic.",
    insights: ["service-experience", "market-context"], levers: ["operations", "health-communication", "digital-gtm"], outcomes: ["reach-access", "human-health"],
  },
  {
    id: "praava-traveler", organization: "Praava", organizationLabel: "Praava / Primary healthcare", sector: "Primary healthcare", market: "bd", year: 2021, lens: "Health-Tech",
    metric: "6-hour results", title: "Traveler testing + door-to-door access",
    summary: "A first-in-country protocol connected sample collection, laboratory operations and government reporting.",
    insights: ["service-experience", "market-context"], levers: ["operations", "ai-systems"], outcomes: ["product-operations", "reach-access", "human-health"],
  },
  {
    id: "praava-diagnostics", organization: "Praava", organizationLabel: "Praava / Primary healthcare", sector: "Primary healthcare", market: "bd", year: 2022, lens: "Population Health",
    metric: "Margin ~30% → ~50%", title: "Ethical, affordable diagnostics",
    summary: "Organ-targeted packages improved affordability and margin without physician kickbacks.",
    insights: ["behavior-signals", "service-experience"], levers: ["brand-strategy", "revenue-growth", "health-communication"], outcomes: ["revenue-pnl", "behavior-brand", "human-health"],
  },
  {
    id: "praava-footfall", organization: "Praava", organizationLabel: "Praava / Primary healthcare", sector: "Primary healthcare", market: "bd", year: 2022, lens: "Growth",
    metric: "~+190% footfall", title: "Winter brand repositioning",
    summary: "Audience insight and integrated communication repositioned the multidisciplinary Beauty & Wellness offer.",
    insights: ["behavior-signals", "market-context"], levers: ["brand-strategy", "digital-gtm", "health-communication"], outcomes: ["behavior-brand", "revenue-pnl"],
  },
  {
    id: "praava-data-engine", organization: "Praava", organizationLabel: "Praava / Primary healthcare", sector: "Primary healthcare", market: "bd", year: 2023, lens: "Health-Tech",
    metric: "~57% B2C CAGR", title: "Data engine for product and growth decisions",
    summary: "BI/Data stayed inside marketing; ARPU, CLV, cohorting and retention shaped product and growth priorities.",
    insights: ["behavior-signals", "service-experience"], levers: ["ai-systems", "revenue-growth", "operations"], outcomes: ["product-operations", "revenue-pnl"],
  },
  {
    id: "lasertreat-digitization", organization: "Laser Treat", organizationLabel: "Laser Treat / Specialized healthcare", sector: "Specialized healthcare", market: "bd", year: 2024, lens: "Health-Tech",
    metric: "+16% revenue · −$0.5M opex", title: "Digitizing a multi-entity clinical group",
    summary: "Centralized ERP, patient records, BI, HR and CX systems connected operational discipline to clinical growth.",
    insights: ["service-experience", "behavior-signals"], levers: ["operations", "ai-systems", "revenue-growth", "health-communication"], outcomes: ["product-operations", "revenue-pnl", "human-health"],
  },
  {
    id: "hsrep-season1", organization: "HSREP", organizationLabel: "HSREP / Public health", sector: "Public health communication", market: "both", year: 2026, lens: "Health Communication",
    metric: "57,274 gross views/impressions", title: "Two-country public-health communication",
    summary: "An independent public-health platform translated health-system evidence into a two-country, eight-week Season 1.",
    insights: ["behavior-signals", "market-context"], levers: ["health-communication", "digital-gtm", "ai-systems"], outcomes: ["reach-access", "behavior-brand", "human-health"],
  },
  {
    id: "emu-harm-reduction", organization: "EMU", organizationLabel: "EMU / Health promotion", sector: "Public health education", market: "us", year: 2025, lens: "Health Communication",
    metric: "Year-long · evaluated", title: "Campus harm-reduction campaign",
    summary: "Audience-segmented, non-judgmental alcohol and cannabis communication was designed with an evaluation framework.",
    insights: ["behavior-signals", "service-experience"], levers: ["health-communication", "brand-strategy"], outcomes: ["behavior-brand", "human-health"],
  },
  {
    id: "emu-residence", organization: "EMU", organizationLabel: "EMU / Residence life", sector: "Education & community", market: "us", year: 2026, lens: "Population Health",
    metric: "541 engagements", title: "Residence-life communication system",
    summary: "Audience-segmentation training and a structured engagement system strengthened resident connection.",
    insights: ["service-experience", "behavior-signals"], levers: ["operations", "health-communication", "ai-systems"], outcomes: ["reach-access", "behavior-brand"],
  },
  {
    id: "surecash-g2p", organization: "SureCash", organizationLabel: "SureCash / Fintech + government", sector: "Fintech & government", market: "bd", year: 2016, lens: "Population Health",
    metric: "~10M beneficiaries", title: "Government stipend delivery at national scale",
    summary: "Residence-mapped POS materials, automated calls and rural mosque activation helped reach ten million beneficiaries.",
    insights: ["customer-conversations", "market-context"], levers: ["digital-gtm", "operations", "brand-strategy"], outcomes: ["reach-access", "product-operations"],
  },
  {
    id: "ekhanei-category", organization: "Ekhanei", organizationLabel: "Ekhanei / E-commerce", sector: "E-commerce", market: "bd", year: 2017, lens: "Growth",
    metric: "#1 in 2.5 months", title: "Bangladesh's #1 motorbike category",
    summary: "A nationwide category system combined market insight, seller operations, quality control and brand communication.",
    insights: ["market-context", "behavior-signals", "service-experience"], levers: ["brand-strategy", "operations", "revenue-growth"], outcomes: ["market-leadership", "revenue-pnl", "behavior-brand"],
  },
  {
    id: "ekhanei-bike-bazaar", organization: "Ekhanei", organizationLabel: "Ekhanei / E-commerce", sector: "E-commerce", market: "bd", year: 2017, lens: "Growth",
    metric: "30% sold in a day", title: "Bike Bazaar trust play",
    summary: "Free mechanic checks and vehicle-registration verification converted trust into marketplace transactions.",
    insights: ["behavior-signals", "service-experience"], levers: ["brand-strategy", "digital-gtm"], outcomes: ["behavior-brand", "revenue-pnl"],
  },
  {
    id: "acca-ecosystem", organization: "ACCA", organizationLabel: "ACCA / Professional education", sector: "Professional education", market: "bd", year: 2021, lens: "Growth",
    metric: "100% of targets", title: "Member-growth ecosystem",
    summary: "A KPI-linked employer and member operating model grew conversion, retention and approved employers.",
    insights: ["market-context", "service-experience"], levers: ["operations", "revenue-growth", "brand-strategy"], outcomes: ["revenue-pnl", "product-operations", "behavior-brand"],
  },
  {
    id: "acca-thought-leadership", organization: "ACCA", organizationLabel: "ACCA / Professional education", sector: "Professional education", market: "bd", year: 2020, lens: "Growth",
    metric: "National media", title: "Flagship thought leadership",
    summary: "Round tables, partnerships and flagship ceremonies connected professional insight to national institutions and media.",
    insights: ["market-context", "behavior-signals"], levers: ["brand-strategy", "digital-gtm"], outcomes: ["reach-access", "behavior-brand"],
  },
  {
    id: "asiatic-lux", organization: "Asiatic", organizationLabel: "Asiatic / Brand + digital", sector: "Advertising & digital", market: "bd", year: 2014, lens: "Growth",
    metric: "~10,000 applicants", title: "Lux Channel i Superstar 2014",
    summary: "A twelve-episode national platform connected audience attention, television production, online voting and a live finale.",
    insights: ["behavior-signals", "market-context"], levers: ["brand-strategy", "digital-gtm", "operations"], outcomes: ["reach-access", "behavior-brand"],
  },
  {
    id: "asiatic-digital", organization: "Asiatic", organizationLabel: "Asiatic / Brand + digital", sector: "Advertising & digital", market: "bd", year: 2015, lens: "Growth",
    metric: "~$1M/month in 7 months", title: "Building Asiatic Digital",
    summary: "A dedicated digital P&L turned digital strategy into a scaled agency practice and retainer engine.",
    insights: ["market-context", "behavior-signals"], levers: ["digital-gtm", "brand-strategy", "revenue-growth", "operations"], outcomes: ["revenue-pnl", "product-operations", "behavior-brand"],
  },
].map((item) => ({ ...item, tenure: tenureByOrg[item.organization] }));

export const impactSummary = {
  reach: [
    { metric: "10M", detail: "beneficiaries reached through national G2P delivery (SureCash)" },
    { metric: "~3.6M", detail: "people served during the pandemic, approximately 2% of Bangladesh (Praava)" },
    { metric: "57,274", detail: "gross platform-reported views and impressions at $0 ad spend across two countries (HSREP)" },
  ],
  press: { metric: "19 mentions", detail: "across 12 TV, print and digital outlets" },
  capability: [["Growth", 7], ["Brand & GTM", 5], ["Behavior", 4], ["Operations", 3], ["Product", 2]],
  thinking: [["Growth", 25], ["AI", 20], ["Health-Tech", 22], ["Public Health", 22]],
};

export const marketCopy = {
  bd: {
    title: "Bangladesh",
    eyebrow: "Proven scale",
    subtitle: "Sixteen years of commercial, operational and healthcare outcomes.",
    facts: [
      ["18 results", "measured evidence across national and organizational systems"],
      ["10M", "beneficiaries reached on national G2P rails"],
      ["~2%", "of Bangladesh served during the pandemic"],
      ["#1", "globally for Galaxy Note9 launch growth"],
      ["342 → ~1,400", "corporate healthcare clients built from zero"],
    ],
  },
  us: {
    title: "United States",
    eyebrow: "Public-health foundation",
    subtitle: "Credentialed practice and emerging evidence in a new market.",
    facts: [
      ["MPH", "Health Education & Promotion, 2026"],
      ["CHES®", "national health-education credential"],
      ["Year-long", "evaluated campus harm-reduction campaign"],
      ["541", "documented residence-life engagements"],
      ["10,000+", "public-health column amplification"],
    ],
  },
};
